#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BottomToolbar.Resource", IsApplication=true)]

namespace BottomToolbar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000b
			public const int aqua = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int black = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int blue = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int dark_grey = 2131034130;
			
			// aapt resource value: 0x7f050004
			public const int fuchsia = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int green = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int grey = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int lime = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int maroon = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int navy = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int olive = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int purple = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int red = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int silver = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int teal = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int theme_blue = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int theme_green = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int white = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int yellow = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_icon1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_icon2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_icon3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_icon4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pic1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pic2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pic3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pic4 = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int bottomtoolbarmain = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int container = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int content = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int footer = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int footer_border = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int header = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int header_menu_left = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int header_menu_right = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int header_title = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int heading_text = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int main_content = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int menu_left = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int menu_right = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int pic1 = 2131165184;
			
			// aapt resource value: 0x7f07001b
			public const int pic2 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int pic3 = 2131165212;
			
			// aapt resource value: 0x7f070001
			public const int pic4 = 2131165185;
			
			// aapt resource value: 0x7f07000f
			public const int tab1 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int tab1_icon = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int tab1_text = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int tab2 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int tab2_icon = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int tab2_text = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int tab3 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int tab3_icon = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int tab3_text = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int tab4 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int tab4_icon = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int tab4_text = 2131165210;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FirstFragment = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FourthFragment = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SecondFragment = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ThirdFragment = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
